### ISSUE TITLE
codegen, typegen and schema

### ISSUE THREAD

**Issue by geastwood** [litentry/subsquid-mappings#4]
* our api gateway will fetch types directly

It will look something like this:
https://graphql-console.subsquid.io/?graphql_api=https%3A%2F%2Fkusama.indexer.gc.subsquid.io%2Fv4%2Fgraphql

**Comment by bdmason** [comment]
Our Subsquid graph can be accessed here: https://app.gc.subsquid.io/beta/litentry/1/graphql
